/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StudyPlannerRouteImport } from './routes/study-planner'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AiResearchRouteImport } from './routes/ai-research'
import { Route as AiCopilotRouteImport } from './routes/ai-copilot'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyPlannerRoute = StudyPlannerRouteImport.update({
  id: '/study-planner',
  path: '/study-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AiResearchRoute = AiResearchRouteImport.update({
  id: '/ai-research',
  path: '/ai-research',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCopilotRoute = AiCopilotRouteImport.update({
  id: '/ai-copilot',
  path: '/ai-copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-copilot': typeof AiCopilotRoute
  '/ai-research': typeof AiResearchRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/study-planner': typeof StudyPlannerRoute
  '/support': typeof SupportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-copilot': typeof AiCopilotRoute
  '/ai-research': typeof AiResearchRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/study-planner': typeof StudyPlannerRoute
  '/support': typeof SupportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-copilot': typeof AiCopilotRoute
  '/ai-research': typeof AiResearchRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/study-planner': typeof StudyPlannerRoute
  '/support': typeof SupportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-copilot'
    | '/ai-research'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/get-started'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/study-planner'
    | '/support'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-copilot'
    | '/ai-research'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/get-started'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/study-planner'
    | '/support'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-copilot'
    | '/ai-research'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/get-started'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/study-planner'
    | '/support'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiCopilotRoute: typeof AiCopilotRoute
  AiResearchRoute: typeof AiResearchRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FeaturesRoute: typeof FeaturesRoute
  GetStartedRoute: typeof GetStartedRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  StudyPlannerRoute: typeof StudyPlannerRoute
  SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-planner': {
      id: '/study-planner'
      path: '/study-planner'
      fullPath: '/study-planner'
      preLoaderRoute: typeof StudyPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-research': {
      id: '/ai-research'
      path: '/ai-research'
      fullPath: '/ai-research'
      preLoaderRoute: typeof AiResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-copilot': {
      id: '/ai-copilot'
      path: '/ai-copilot'
      fullPath: '/ai-copilot'
      preLoaderRoute: typeof AiCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiCopilotRoute: AiCopilotRoute,
  AiResearchRoute: AiResearchRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FeaturesRoute: FeaturesRoute,
  GetStartedRoute: GetStartedRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  StudyPlannerRoute: StudyPlannerRoute,
  SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
